### ISSUE TITLE
Every SRT encoder returns Bad Parameter

### ISSUE THREAD

**Issue by rebotnix** [Eyevinn/node-srt#15] opened 2020-11-07 19:18 UTC
I tested the latest version and i got no connect with any hardware SRT encoder.

I simply use this as a server setup:
const fs = require('fs');
const dest = fs.createWriteStream('./output');
const { SRTReadStream } = require('@eyevinn/srt');

// local intranet
const srt = new SRTReadStream('172.28.115.51', 1234);
srt.listen(readStream => {
  readStream.pipe(dest);
});

To reproduce encoder, you can try OBS Encoder and set the output stream to where i set:
srt://172.28.115.51:1234

Console output when OBS connect is:
/opt/4tbdrive1/experiments/nodejs_srt/node_modules/@eyevinn/srt/src/srt-stream-readable.js:83
          const fhandle = this.srt.accept(this.socket);
                                   ^
Error: Operation not supported: Bad parameters
    at /opt/4tbdrive1/experiments/nodejs_srt/node_modules/@eyevinn/srt/src/srt-stream-readable.js:83:36
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (/opt/4tbdrive1/experiments/nodejs_srt/node_modules/@eyevinn/srt/src/srt-stream-readable.js:75:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

When i use the stand alone srt-live-transmit (compiled from your npm install tree) all is working fine.

Do you know this issue?

**Comment by birme** [comment] 2020-11-09 10:20
Hi,

Thank you for the report. We'll look into this.

/Jonas

**Comment by birme** [comment] 2020-11-09 10:27
I did not manage to reproduce this issue on my laptop using OBS encoder.

Just to test could you change `const srt = new SRTReadStream('172.28.115.51', 1234);` to `const srt = new SRTReadStream('0.0.0.0', 1234);` and then stream output to 172.28.115.51 from OBS.
To see if it is related to binding the port to a specific interface.
Thanks!

**Comment by tchakabam** [comment] 2020-11-12 19:42
@rebotnix please consider my comment [here](https://github.com/Eyevinn/node-srt/issues/16#issuecomment-726298800) also for improving this issue post. thanks :)

**Comment by tchakabam** [comment] 2020-11-12 19:50
So, I guess we established that this `Bad parameters` error happens only in your setup. Unrelated to which type of API you are using here and in what type of example code. 

It is thrown by SRT native binding code as a result of an internal error when running the `accept` method, but that is because the connection attempt failed for a reason libSRT prints this specific message :)

However, this seems to be much related to something specific in your setup.

Maybe you could ask in the SRT Slack chat about what this error is, or check further in the libSRT code base.

I could imagine that the SRT URL parameters that you set on the encoder side are not valid. What are you using in terms of URL on the encoder side?

Also: What SRT version is this encoder using that you are running?

**Comment by tchakabam** [comment] 2021-03-03 14:30
It seems this is an SRT versions incompatibility issue, see https://github.com/Eyevinn/node-srt/issues/17

I am unsure yet wether we need to fix something in this codebase, or if it is to be addressed by a libSRT patch.

**Closed as completed** 2021-03-03 16:13 UTC
